# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171103_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 5, 18, 33, 588463, tzinfo=utc)),
        ),
    ]
